const student = [{
    "id": 1,
    "first_name": "Charlotta",
    "last_name": "Wassell",
    "email": "cwassell0@stanford.edu",
    "gender": "Female"
  }, {
    "id": 2,
    "first_name": "Marion",
    "last_name": "Wordington",
    "email": "mwordington1@hugedomains.com",
    "gender": "Male"
  }, {
    "id": 3,
    "first_name": "Todd",
    "last_name": "Curragh",
    "email": "tcurragh2@fema.gov",
    "gender": "Male"
  }, {
    "id": 4,
    "first_name": "Kris",
    "last_name": "Healey",
    "email": "khealey3@chron.com",
    "gender": "Female"
  }, {
    "id": 5,
    "first_name": "Neron",
    "last_name": "Dunmuir",
    "email": "ndunmuir4@stumbleupon.com",
    "gender": "Male"
  }, {
    "id": 6,
    "first_name": "Mead",
    "last_name": "Hargrave",
    "email": "mhargrave5@mlb.com",
    "gender": "Male"
  }, {
    "id": 7,
    "first_name": "Basile",
    "last_name": "Mughal",
    "email": "bmughal6@blogspot.com",
    "gender": "Male"
  }, {
    "id": 8,
    "first_name": "Thibaut",
    "last_name": "Androlli",
    "email": "tandrolli7@sakura.ne.jp",
    "gender": "Male"
  }, {
    "id": 9,
    "first_name": "Hillel",
    "last_name": "Mullin",
    "email": "hmullin8@indiatimes.com",
    "gender": "Male"
  }, {
    "id": 10,
    "first_name": "Bartel",
    "last_name": "Callan",
    "email": "bcallan9@printfriendly.com",
    "gender": "Male"
  }]

  module.exports = student;